- debug:
    msg: "restoring from /backup/{{ rollback_date }}/{{ inventory_hostname }}.txt"

- name: restore the config
  arista.eos.config:
    replace: config
    src: "/tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt"

- name: print to terminal window
  debug:
    msg: "Restore is complete for device {{ inventory_hostname }} is set to {{ rollback_date }} timestamp"
