# This task will backup the configuration
- name: backup the configuration
  ios_config:
    backup: yes
  register: config_output

# This task removes the Current configuration... from the top of IOS routers show run
- name: remove non config lines - regexp
  lineinfile:
    path: "{{config_output.backup_path}}"
    line: "Building configuration..."
    state: absent
