---
- name: Gather juniper junos facts
  vars:
    ansible_connection: netconf
  junipernetworks.junos.junos_facts:
    gather_network_resources: "{{ network_resource | default('!vlans,!bgp_global,!bgp_address_family,!ospf_interfaces,!ospf,!ospfv3') }}"
