---
- name: gather juniper junos facts
  vars:
    ansible_connection: netconf
  junipernetworks.junos.junos_facts:
    gather_subset: config
    gather_network_resources: "{{ network_resource | default('all') }}"
