- name: gather network device facts
  collections:
    - cisco.ios
    - arista.eos
    - junipernetworks.junos
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/{{ ansible_network_os }}.yml"
    - "{{ role_path }}/tasks/unsupported_platform.yml"

- name: display facts
  debug:
    var: ansible_network_resources
