---
- name: configure network VLANs
  hosts: all
  gather_facts: no
  vars:
    - vlan_state:  "{{ net_vlan_state | default('merged') }}"
    - vlan_config: "{{ net_vlan_config | default('') }}"

  # you would pass vlan_config like this:
  # ---
  # net_vlan_config:
  # - name: desktops
  #   vlan_id: 5
  # - name: servers
  #   vlan_id: 10
  # - name: dmz
  #   vlan_id: 20

  tasks:
    - name: transform vlan_config into dictionary if coming from controller
      set_fact:
        vlan_config: "{{ net_vlan_config | from_yaml }}"
      when: net_vlan_config is mapping

    - name: assert that VLAN config was sent
      assert:
        that:
          - vlan_config != ''
        fail_msg: "no 'vlan_config' was sent, please send a valid configuration set as the variable net_vlan_config"
        success_msg: "all assertions passed"

    # if using this role from the collection it would be network.toolkit.vlans
    - name: include correct role for network device type
      include_role:
        name: "../roles/vlans"
      when: ansible_network_os is defined
