---
- name: configure network VLANs
  hosts: all
  gather_facts: no

  tasks:
    # if using this role from the collection it would be network.toolkit.vlans
    - name: include correct role for network device type
      include_role:
        name: "../roles/vlans"
      when: ansible_network_os is defined
