---
- name: Restore router configurations
  hosts: network
  gather_facts: false
  vars:
    restore_mode: overwrite

  tasks:
    - name: Retreive configuration from backup-server to execution environment
      ansible.builtin.fetch:
        src: "/backup/{{ rollback_date }}/{{ inventory_hostname }}.txt"
        dest: "/tmp/{{ rollback_date }}/"
        flat: true
      delegate_to: backup-server
      when: ansible_network_os is defined

    - name: Load restore role
      ansible.builtin.include_role:
        name: "../roles/restore"
      when: ansible_network_os is defined
